-- ============================================================
-- stg_raw_orders.sql
-- IntelliPipe Staging Model: Raw Order Events
-- ============================================================
-- Applies type casting, null handling, and enum validation
-- on top of the raw Kafka-landed events table.
-- All DQ fixes generated by IntelliPipe LLM agent are applied
-- in dedicated CTEs for full auditability.
-- ============================================================

with

source as (
    select * from {{ source('intellipipe_raw', 'raw_orders') }}
    where _loaded_at >= dateadd('hour', -25, current_timestamp)  -- Incremental window
),

-- ── Fix: Cast and validate critical fields ──────────────────
type_casted as (
    select
        event_id::varchar(64)                                       as event_id,
        event_type::varchar(32)                                     as event_type,
        tenant_id::varchar(64)                                      as tenant_id,
        order_id::varchar(32)                                       as order_id,
        customer_id::varchar(32)                                    as customer_id,

        -- Email normalization + null safety
        lower(trim(nullif(customer_email, '')))                     as customer_email,

        -- Enum validation: map invalid statuses to NULL
        case
            when lower(order_status) in (
                'pending', 'confirmed', 'shipped',
                'delivered', 'cancelled', 'refunded'
            ) then lower(order_status)
            else null
        end                                                         as order_status,

        -- Payment method validation
        case
            when lower(payment_method) in (
                'credit_card', 'debit_card', 'paypal',
                'crypto', 'wire_transfer'
            ) then lower(payment_method)
            else null
        end                                                         as payment_method,

        -- Amount safety: clip negative values
        greatest(coalesce(subtotal::numeric(18,2), 0), 0)          as subtotal,
        greatest(coalesce(tax_amount::numeric(18,2), 0), 0)        as tax_amount,
        greatest(coalesce(shipping_amount::numeric(18,2), 0), 0)   as shipping_amount,
        greatest(coalesce(total_amount::numeric(18,2), 0), 0)      as total_amount,

        upper(nullif(trim(currency), ''))                           as currency,
        upper(nullif(trim(shipping_country), ''))                  as shipping_country,
        nullif(trim(shipping_city), '')                            as shipping_city,

        -- Timestamp handling: reject events older than 7 days
        case
            when event_timestamp::timestamp with time zone
                 < current_timestamp - interval '7 days'
            then null
            else event_timestamp::timestamp with time zone
        end                                                         as event_timestamp,

        created_at::timestamp with time zone                       as created_at,
        schema_version::varchar(8)                                 as schema_version,
        source_system::varchar(64)                                 as source_system,
        partition_date::date                                       as partition_date,

        -- Pipeline metadata
        _loaded_at                                                  as _loaded_at,
        current_timestamp                                          as _dbt_processed_at

    from source
),

-- ── Fix: Recalculate totals where inconsistent ───────────────
amount_reconciled as (
    select
        *,
        -- Flag rows where total deviates from components by >$0.10
        abs(total_amount - (subtotal + tax_amount + shipping_amount)) as amount_discrepancy,
        case
            when abs(total_amount - (subtotal + tax_amount + shipping_amount)) > 0.10
            then subtotal + tax_amount + shipping_amount  -- Recompute from components
            else total_amount
        end                                                         as total_amount_reconciled

    from type_casted
),

-- ── Deduplication: keep latest event per order_id ────────────
deduplicated as (
    select *
    from (
        select
            *,
            row_number() over (
                partition by order_id, tenant_id
                order by coalesce(event_timestamp, created_at) desc
            ) as _row_num
        from amount_reconciled
    )
    where _row_num = 1
),

-- ── Final: add DQ quality flags ──────────────────────────────
final as (
    select
        -- Core fields
        event_id,
        event_type,
        tenant_id,
        order_id,
        customer_id,
        customer_email,
        order_status,
        payment_method,
        subtotal,
        tax_amount,
        shipping_amount,
        total_amount_reconciled                                     as total_amount,
        currency,
        shipping_country,
        shipping_city,
        event_timestamp,
        created_at,
        schema_version,
        source_system,
        partition_date,

        -- DQ quality flags (useful for downstream consumers)
        (order_status is null)                                      as has_invalid_status,
        (payment_method is null)                                    as has_invalid_payment_method,
        (customer_email is null)                                    as has_null_email,
        (event_timestamp is null)                                   as has_stale_timestamp,
        (amount_discrepancy > 0.10)                                as has_amount_discrepancy,

        -- Overall row quality score (simple heuristic)
        round(
            100.0
            - (case when order_status is null then 20 else 0 end)
            - (case when payment_method is null then 15 else 0 end)
            - (case when customer_email is null then 10 else 0 end)
            - (case when event_timestamp is null then 25 else 0 end)
            - (case when amount_discrepancy > 0.10 then 10 else 0 end)
        , 0)                                                        as row_quality_score,

        _loaded_at,
        _dbt_processed_at

    from deduplicated
)

select * from final
